name: IAC CI & CD

on:
  push:
    branches:
      - master
    paths:
      - 'iac/**'
      - '.github/workflows/iac.workflow.yml'

env:
  ACTIONS_RUNNER_DEBUG: true

defaults:
  run:
    working-directory: iac

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Generate parameters file
        uses: azure/CLI@v1
        with:
          azcliversion: 2.55.0
          inlineScript: |
            az bicep install
            az bicep version
            az bicep build-params --file iac/prd.bicepparam

      - name: Deploy
        uses: azure/CLI@v1
        with:
          azcliversion: 2.55.0
          inlineScript: |
            az deployment group create --name deployment-reservation-prd --resource-group Reservation --template-file iac/main.bicep --parameters iac/prd.json

      # - name: deploy
      #   uses: azure/arm-deploy@v1
      #   with:
      #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #     resourceGroupName: ${{ secrets.AZURE_RG }}
      #     template: iac/main.bicep
      #     parameters: iac/prd.json
      #     failOnStdErr: false